# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemple.mp3"
Content-Type: exemple/mpeg

< ./exemple.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/0835c7b7-55f0-4209-8605-e1b996cdac6a/transcription
Content-Type: application/json

{
  "prompt": "ultra realista, rockstar, gta iv"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "b7224ddf-d2e5-4695-8e3c-dbdcdb7a6896",
  "temperature": 0.5,
  "prompt": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}

###

# @name create-user

POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "Natália Pereira",
  "email": "nath.licha@edu.unifil.br",
  "password": "nath123"
}

###

# @name login-user

POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "mateus.campaner@edu.unifil.br",
  "password": "senha321"
}

###

# @name edit-user

PUT http://localhost:3333/edit-profile/8a60cc9d-5c99-43a0-bdaf-8fe789b9cdc8
Content-Type: application/json

{
  "name": "Gabriel Gonçalves Pereira",
  "password": "Nino9172@"
}